<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.26100.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
    <RootNamespace>TinyWin2.Gui</RootNamespace>
    <AssemblyName>TinyWin2.Gui</AssemblyName>
    <UseWinUI>true</UseWinUI>
    <WindowsPackageType>None</WindowsPackageType>
    <WindowsAppSDKSelfContained>true</WindowsAppSDKSelfContained>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <CsWinRTAotOptimizerEnabled>true</CsWinRTAotOptimizerEnabled>
    <PublishAot>true</PublishAot>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>full</TrimMode>
    <OptimizationPreference>Speed</OptimizationPreference>
    <SatelliteResourceLanguages>zh-CN;en-US</SatelliteResourceLanguages>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <Optimize>true</Optimize>
    <DebuggerSupport>false</DebuggerSupport>
    <EventSourceSupport>false</EventSourceSupport>
    <MetricsSupport>false</MetricsSupport>
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <StripSymbols>true</StripSymbols>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4129.50"/>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.28000.2526"/>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools.MSIX" Version="1.7.260610101"/>
    <PackageReference Include="Microsoft.WindowsAppSDK.InteractiveExperiences" Version="2.1.6"/>
    <PackageReference Include="Microsoft.WindowsAppSDK.WinUI" Version="2.3.6"/>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TinyWin2.Core\TinyWin2.Core.csproj"/>
  </ItemGroup>
</Project>
